// 
// Code generated by Identity and Access VS Package
// 

using System.Globalization;
using System.Web.Mvc;

namespace HrdAuthentication.Controllers
{
    public class HrdAuthenticationController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login()
        {
            ViewBag.MetaDataScript = "https://crmfederation.accesscontrol.windows.net/v2/metadata/identityProviders.js?protocol=wsfederation&realm=http://127.0.0.1:81/&version=1.0&callback=ShowSigninPage";
            return View("~/Views/HrdAuthentication/Login.cshtml");
        }
    }
}
